name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: cache
        key: workflow
        
    - name: npm install, build
      run: |
        npm install
        npm run build
    
    - name: Release Github Pages
      uses: igolopolosov/github-action-release-github-pages@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.token }}
        GITHUB_PAGES_REPO_AUTHOR: jarvis394
        GITHUB_PAGES_REPO_NAME: habra.github.io
        GITHUB_PAGES_RELEASE_BRANCH: master
        PROJECT_BUILD_FOLDER: build
        GITHUB_PAGES_CLEANUP_SCRIPT: "rm -rf build"
